# docker-compose.yaml
services:
  lotto-predictor:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.python
    command: python3 ./main.py ${DATE:-20221111} ${WHEEL:-MI}
    volumes:
      - ./app:/usr/app/src:delegated
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python3", "-c", "import pandas; import sklearn"]
      interval: 30s
      timeout: 10s
      retries: 3