version: "3.8"
services:
  python:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.python
    command: python3 ./oracolo.py 20221111 MI
    volumes:
      - ./app:/usr/app/src:delegated